name: "unit"
version: "0.1.0-alpha"
usage: "Run unit test on helm chart templates"
description: |-
  Run unit-test on a chart locally without deloying the release.
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-unit -h"

hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"