tests:
  - description: Run the following test on Ingress 
    type: Ingress
    name: demo-ing
    asserts:
    - name: check ingress path
      type: contains
      values:
      - path: spec.rules[*].http.paths[*].path
        value: /api
    - name: check that metadata labels are set and not empty
      type: isNotEmpty
      values:
      - path: metadata.labels