  
version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip install -r requirements.txt
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          name: Test
      - run:
          command: |
            curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.7.0/kind-$(uname)-amd64
            wget -q https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz
            wget -q https://storage.googleapis.com/kubernetes-release/release/v1.16.0/bin/linux/amd64/kubectl
            chmod +x ./kind
            chmod +x kubectl
            sudo tar -xzvf helm-v3.2.0-linux-amd64.tar.gz
            chmod +x linux-amd64/helm
            sudo mv kubectl /usr/local/bin
            sudo mv ./kind /usr/local/bin/kind
            sudo mv linux-amd64/helm /usr/local/bin
            kubectl version --client
            helm version
            kind version
            kind create cluster
          name: setup kind

workflows:
  main:
    jobs:
      - build-and-test